server:
  port: 8888
  
amazon:
  associateId: habuma-20
  
info:
  contact:
      Email: 2Be@2Do.wins
      Email2: tudoistube@ymail.com
      phone: 82-10-2345-6789
      
#...234p.      
management:
  context-path: /zmgmt      
  
---
  
spring:
  profiles: development
  
logging:
  level:
    root: error